export const CANVAS_SECTION = Object.freeze({
    PROBLEM: 'PROBLEM',
    SOLUTION: 'SOLUTION',
    CUSTOMER_SEGMENTS: 'CUSTOMER_SEGMENTS',
    VALUE_PROPOSITION: 'VALUE_PROPOSITION',
    UNFAIR_ADVANTAGE: 'UNFAIR_ADVANTAGE',
    CHANNELS: 'CHANNELS',
    KEY_METRICS: 'KEY_METRICS',
    COST_STRUCTURE: 'COST_STRUCTURE',
    REVENUE_STREAMS: 'REVENUE_STREAMS',
    EXISTING_ALTERNATIVES: 'EXISTING_ALTERNATIVES',
    HIGH_LEVEL_CONCEPT: 'HIGH_LEVEL_CONCEPT',
    EARLY_ADOPTERS: 'EARLY_ADOPTERS',
});